### ISSUE TITLE
Docker image for Arm64 platform is required 

### ISSUE THREAD

**Issue by odidev** [brigadecore/go-tools#2]
Hi Team,
I am trying to use the **go-tools** image on arm64 platform but it seems it is not available for arm64.
I have successfully built the image using the command `docker build -t <image_name> .` on the arm64 platform with no change.
Do you have any plans on releasing arm64 image?
I've successfully pushed the image on my dockerhub using Travis-CI. May I know how the amd64 image is getting published on Dockerhub?
If interested, I will raise a PR.

**Comment by krancour** [comment]
Closing due to staleness. This issue will be subsumed by a larger effort to get all of Brigade working on arm64 post v2.
